### ISSUE TITLE
能够写一个样例吗

### ISSUE THREAD

**Issue by liujingjie** [Vicfeel/OTMaps#3]
你好，我刚开始学arcgis  的js API，看到这个项目很开心，但是该如何使用还是不太懂，能写一个样例吗？

**Comment by Vicfeel** [comment]
可以的，本周会增加使用样例

**Comment by liujingjie** [comment]
在rangemap中绘制专题图的时候总是会引发跨域问题，不知道您是怎么解决的。

**Comment by Vicfeel** [comment]
``` js
esriConfig.defaults.io.corsDetection = false;//解决跨域请求
```

&emsp; 其它几个专题图的使用案例也已上线，有不清楚的可以继续讨论。
&emsp; 在线专题图不止目前这几类，欢迎一起参与到开发中来
